language: node_js
branches:
  only:
    - master
notification:
  recipients:
    - yangtopia@gmail.com
env:
  global:
    - DOCKER_USER=yangtopia
    - DOCKER_PASS=Wlsrb0312!@
deploy:
  provider: script
  script: bash ./bash/docker-deploy.sh
  skip_cleanup: true
  on:
    repo: yangtopia/selfdating-web
    tags: true
