language: node_js
branches:
  only:
    - master
notification:
  recipients:
    - yangtopia@gmail.com
deploy:
  provider: script
  script: bash ./bash/docker-deplay.sh
  on:
    branch: master
    tags: true
