language: node_js
node_js:
  - node
branches:
  only:
    - master
notification:
  recipients:
    - yangtopia@gmail.com
deploy:
  provider: script
  script: bash ./bash/docker-deploy.sh
  on:
    branch: master
    tags: true
